version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    restart: on-failure
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: docker.for.mac.localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: on-failure
  scylla:
    image: scylladb/scylla
    ports:
      - "9042:9042"
    command: "--broadcast-address 127.0.0.1 --broadcast-rpc-address 127.0.0.1"
    restart: on-failure
  java:
    build: 
      context: .
      dockerfile: java.dockerfile
    ports:
      - "5005:5005"
    depends_on:
      - zookeeper
      - kafka
      - scylla
    restart: on-failure